AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance with Security Group and Web Server Setup

Resources:

  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: vpc-093891b76f1d7b69b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09e6f87a47903347c  
      KeyName: Linux-VA      
      SecurityGroupIds:
        - !Ref WebServerSG
      SubnetId: subnet-09c5b402930f810e0
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Welcome to Aviz Academy EC2 Web Server</h1>" > /var/www/html/index.html


